### ISSUE TITLE
Some Courses don't appear when you enter them

### ISSUE THREAD

**Issue by itschrisL** [upcs/cs-341-project-sq19-golf#32]
When I try entering some courses, they wouldn't appear and others would work just fine.   The course would show up as part of your auto fill so they are probably in your db.  I may have been experiencing some bugs from many people using your app at once.  Maybe report a warning to the user that a course's class time is not available.

Ex. 
CS 421/521
CS 483

**Comment by KaitlinLarson** [comment]
My suspicion is that it's only grabbing information from the current semester rather than the specified semester.

**Comment by Katacka** [comment]
![image](https://user-images.githubusercontent.com/38484708/56060536-02dcc100-5d1c-11e9-88ff-a7b3614af0ba.png)

Doing a brief query on self serve, I was not able to find any of the courses you listed above as classes taking place during Fall 2019. There may have been some confusion regarding the ability of this scheduler to reference semesters which are not Fall 2019. As noted in issue https://github.com/upcs/cs-341-project-sq19-golf/issues/34, this will be fixed in the current sprint.
