### ISSUE TITLE
Issue with entering too many classes

### ISSUE THREAD

**Issue by hoangj21** [upcs/cs-341-project-sq19-golf#33]
1) Initially, I tried entering a course combination of CS 203, CS 301, and CS 305. 
2) Schedule was properly outputted
3) I hit return and entered in a new course combination, this time with 7 courses: CS 203, CS 301, CS 305, CS 273, CS 371, ENG 112, SOC 101 (maybe it was too many courses?)
4) Hitting return resulted in it outputting the same schedule as step 1

**Comment by Katacka** [comment]
My suspicion is the courses you entered likely did not feature a valid overlap. I'll look into the issue further to verify this is the case.

**Comment by Katacka** [comment]
![image](https://user-images.githubusercontent.com/38484708/56060271-3b2fcf80-5d1b-11e9-8e01-27d28c3d5638.png)

I was successfully able to generate the schedule you cited by typing the courses in and waiting approximately 4 seconds. Sadly, due to the complexity of the query and the large optimizations we've already added, several second wait times for large schedules are likely the best we can do in the worst case scenario. However, we're looking to add some memoized schedules which could improve the runtime on common requests
